# Generated by Django 4.2.9 on 2024-01-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('phonenumber', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True, max_length=5000)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(blank=True, choices=[('credit', 'credit'), ('debit', 'debit')], max_length=100)),
                ('status', models.CharField(blank=True, choices=[('pending confirmation', 'pending confirmation'), ('submitted for review', 'submitted for review'), ('Awaiting Payment', 'Awaiting Payment'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='pending confirmation', max_length=500)),
                ('witholdingtax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=60)),
                ('amount', models.FloatField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_data', models.JSONField(blank=True, null=True)),
                ('bankdetails', models.JSONField(blank=True, null=True)),
                ('paymentto', models.CharField(blank=True, max_length=100)),
                ('requestuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('affected_area', models.CharField(choices=[('transfer', 'transfer'), ('userdata', 'userdata'), ('passwordreset', 'passwordreset')], default='pending', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('Resolved', 'Resolved')], default='pending', max_length=500)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='latestupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Support', 'Support'), ('Deposit', 'Deposit')], default='Inactive', max_length=500)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('ref', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(blank=True, max_length=500)),
                ('accountnumber', models.CharField(blank=True, max_length=500)),
                ('bankname', models.TextField(blank=True, max_length=5000)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accountdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, default='02928', max_length=500)),
                ('bank_name', models.CharField(blank=True, default='pwb Financial Bank', max_length=500)),
                ('account_number', models.CharField(blank=True, default=234, max_length=500)),
                ('account_name', models.CharField(blank=True, max_length=500, null=True)),
                ('requestuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
